version: "2"

services:
  sonarqube:
    # lts
    image: sonarqube:6.5
    # ports:
    #  - "9000:9000"
    # networks:
    #   - sonarnet
    links:
      - db
    restart: always
    environment:
      SONARQUBE_JDBC_URL:
    labels:
      io.rancher.sidekicks: sonarqube-data
    volumes_from:
      - sonarqube-data
    # volumes:
    #   - /srv/docker/sonarqube/sonarqube:/opt/sonarqube:Z
    #   - sonarqube_conf:/opt/sonarqube/conf
    #   - sonarqube_data:/opt/sonarqube/data
    #   - sonarqube_extensions:/opt/sonarqube/extensions
    #   - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube-data:
    image: library/busybox:latest
    labels:
      # rancher labels
      io.rancher.container.start_once: true
      # io.rancher.container.pull_image: always
    entrypoint:
      - "/bin/true"
    volumes:
      # no es posible que solo sea sonarqube, hay que mapear cada carpeta
       - /srv/docker/sonarqube/sonarqube/conf:/opt/sonarqube/conf:Z
       - /srv/docker/sonarqube/sonarqube/data:/opt/sonarqube/data:Z
       - /srv/docker/sonarqube/sonarqube/extensions:/opt/sonarqube/extensions:Z
      # la imagen de sonarqube trae plugins instalados por defecto, por lo que al mapear
      # un volume esto esconde esos plugins. Es necesario instalar los plugins para analizar
       - /srv/docker/sonarqube/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins:Z
      #tty: true
      #stdin_open: true

  db:
    image: postgres:9.6.4
    # networks:
    #   - sonarnet
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
    # Crear un contenedor sidekick para cada volume
      - /srv/docker/sonarqube/postgresql:/var/lib/postgresql:Z # pq Z?
    #   - postgresql:/var/lib/postgresql
    # INVESTIGAR BIEN ESTE TEMA: Muchos de los servicios de CI no crean un volume
    # para mapear /postgresql/data
    #   # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
    #   - postgresql_data:/var/lib/postgresql/data

# networks:
#   sonarnet:
#     driver: bridge

# volumes:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_bundled-plugins:
#   postgresql:
#   postgresql_data:
